### ISSUE TITLE
What am I doing wrong? Project settings

### ISSUE THREAD

**Issue by stoivo** [SublimeLinter/SublimeLinter-pycodestyle#3]
My project settings look like 
```
    "SublimeLinter":{
        "linters":{
            "pycodestyle": {
                "ignore": "E401",
                // E401 multiple imports on one line
                "max-line-length": 120
            }
        }
    },
```
I wonder why `max-line-length` is not picked up?

**Comment by ergdev** [comment]
Hey, please see issue https://github.com/SublimeLinter/SublimeLinter-pycodestyle/issues/2. We are waiting for version 4 of sublime linter. These config settings will deprecated then.

**Comment by stoivo** [comment]
I agree with https://github.com/SublimeLinter/SublimeLinter-pycodestyle/issues/2#issuecomment-354593596 and will switch to setup.cfg. Which I agree on it better.

**Comment by nicbou** [comment]
Could someone explain what this setup.cfg is referring to? Is it a feature of Sublime? SublimeLinter? Pycodestyle? It would save us a lot of research, since both tickets on this topic were closed without much information.

**Comment by stoivo** [comment]
pycodestyle reads setup.cfg. So you can configute pycodestyle in in setup.cfg. I think it is better because so you can run in from the terminal / CI.

Also you probably want to use flake8 instead of pycodestyle.
