### ISSUE TITLE
Docs on how to configure auto-pep8 formatting?

### ISSUE THREAD

**Issue by achilds-vela** [SublimeLinter/SublimeLinter-pycodestyle#8]
I can't tell if this plugin supports auto-formatting of PEP8 or not, or if it does how such a thing would be configured. The links provided in the README also do not explain that.

**Comment by braver** [comment]
Currently SublimeLinter does not support running fixers or formatters. The infrastructure is simply not set up to deal with the idea that running the linter might have the side effect of changing the buffer. We’ve been discussing this for a while now, but it’s not trivial to say the least. I’m sure that when we do start supporting formatters etc. we’ll make a ruckus about it 😄
